// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqhrOEMFebiRxPnDFD_R0vDipgcVMDqdQ',
    appId: '1:303653682889:web:38a1b146d9e1eecb2ad718',
    messagingSenderId: '303653682889',
    projectId: 'nabeeh-3d93d',
    authDomain: 'nabeeh-3d93d.firebaseapp.com',
    storageBucket: 'nabeeh-3d93d.firebasestorage.app',
    measurementId: 'G-NKHD0F65B4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_9QdsTLUeKKwXWFccOJi3qjowCmhQ_D0',
    appId: '1:303653682889:android:0324147f9901d1c52ad718',
    messagingSenderId: '303653682889',
    projectId: 'nabeeh-3d93d',
    storageBucket: 'nabeeh-3d93d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1Amib2ae-yp600Rd7PFcxS7h2FfaGccM',
    appId: '1:303653682889:ios:3b906b7dde66c2ed2ad718',
    messagingSenderId: '303653682889',
    projectId: 'nabeeh-3d93d',
    storageBucket: 'nabeeh-3d93d.firebasestorage.app',
    androidClientId: '303653682889-hd0rn5kiducimgjd77hthg044lc1haoo.apps.googleusercontent.com',
    iosClientId: '303653682889-4dcpvpmm3fm2qe0lvd1b0lodkscsuh99.apps.googleusercontent.com',
    iosBundleId: 'com.example.nabbeh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1Amib2ae-yp600Rd7PFcxS7h2FfaGccM',
    appId: '1:303653682889:ios:3b906b7dde66c2ed2ad718',
    messagingSenderId: '303653682889',
    projectId: 'nabeeh-3d93d',
    storageBucket: 'nabeeh-3d93d.firebasestorage.app',
    androidClientId: '303653682889-hd0rn5kiducimgjd77hthg044lc1haoo.apps.googleusercontent.com',
    iosClientId: '303653682889-4dcpvpmm3fm2qe0lvd1b0lodkscsuh99.apps.googleusercontent.com',
    iosBundleId: 'com.example.nabbeh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqhrOEMFebiRxPnDFD_R0vDipgcVMDqdQ',
    appId: '1:303653682889:web:0009eaf6c0c7b26a2ad718',
    messagingSenderId: '303653682889',
    projectId: 'nabeeh-3d93d',
    authDomain: 'nabeeh-3d93d.firebaseapp.com',
    storageBucket: 'nabeeh-3d93d.firebasestorage.app',
    measurementId: 'G-13Y4N5NMHT',
  );
}
